services:
  nginx:
    image: nginx:1.29
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8080:80"
    depends_on:
      - api
    networks:
      - web
      - api
  web:
    container_name: web_dev
    build:
      context: .
      dockerfile: ./web/Dockerfile
    env_file:
      - ./web/.env.development
    volumes:
      - ./web:/usr/src/app/web
    networks:
      - web
  api:
    container_name: api_dev
    build:
      context: .
      dockerfile: ./api/Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - ./api/.env.development
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - ./api:/usr/src/app/api
    networks:
      - api
      - database
      - cache

  postgres:
    container_name: postgres_dev
    image: postgres:16
    shm_size: 128mb
    ports:
      - "5432:5432"
    env_file:
      - ./infra/.env.development
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - database

  redis:
    container_name: redis_dev
    image: redis:8.2.3-alpine
    ports:
      - "6379:6379"
    env_file:
      - ./infra/.env.development
    volumes:
      - redis-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 5s
    networks:
      - cache

volumes:
  postgres-data:
  redis-data:

networks:
  web:
  api:
  database:
  cache:
