services:
  postgres:
    image: postgres:alpine
    restart: always
    shm_size: 128mb
    container_name: skillhub-postgres-dev
    ports:
      - "5432:5432"
    env_file:
      - ./backendnest/.env.db
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "devskillhub", "-d", "dbskillhub"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

volumes: #aprender sobre isso
  postgres-data:
