services:
  nginx:
    image: nginx:1.29
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8080:80"
    depends_on:
      - api
    networks:
      - api
      - web
  web:
    container_name: web_prod
    build:
      context: .
      dockerfile: ./web/prod.Dockerfile
    networks:
      - web
  api:
    container_name: api_prod
    build:
      context: .
      dockerfile: ./api/prod.Dockerfile
    env_file:
      - ./api/.env.production
    depends_on:
      postgres:
        condition: service_healthy
      redis-cache:
        condition: service_healthy
    networks:
      - api
      - database
      - cache
      - queue

  postgres:
    container_name: postgres_prod
    image: postgres:16
    shm_size: 128mb
    env_file:
      - ./api/.env.production
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - database

  redis-cache:
    container_name: cache_prod
    image: redis:8.2.3-alpine
    volumes:
      - redis-cache-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 5s
    networks:
      - cache

  redis-queue:
    container_name: queue_prod
    image: redis:8.2.3-alpine
    command: ["redis-server", "--maxmemory-policy", "noeviction"]
    volumes:
      - redis-queue-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 5s
    networks:
      - queue

volumes:
  postgres-data:
  redis-cache-data:
  redis-queue-data:

networks:
  web:
  api:
  database:
  cache:
  queue:
